# Generated by Django 3.2.13 on 2022-11-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(default=3, max_length=40),
            preserve_default=False,
        ),
    ]
