# Generated by Django 3.2.13 on 2022-11-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_thumbnail',
        ),
    ]
